/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { TypedEventDescription, TypedFunctionDescription } from ".";

interface ERC165UpgradeableInterface extends Interface {
  functions: {
    supportsInterface: TypedFunctionDescription<{
      encode([interfaceId]: [Arrayish]): string;
    }>;
  };

  events: {};
}

export class ERC165Upgradeable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ERC165Upgradeable;
  attach(addressOrName: string): ERC165Upgradeable;
  deployed(): Promise<ERC165Upgradeable>;

  on(event: EventFilter | string, listener: Listener): ERC165Upgradeable;
  once(event: EventFilter | string, listener: Listener): ERC165Upgradeable;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ERC165Upgradeable;
  removeAllListeners(eventName: EventFilter | string): ERC165Upgradeable;
  removeListener(eventName: any, listener: Listener): ERC165Upgradeable;

  interface: ERC165UpgradeableInterface;

  functions: {
    /**
     * See {IERC165-supportsInterface}.
     */
    supportsInterface(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    /**
     * See {IERC165-supportsInterface}.
     */
    "supportsInterface(bytes4)"(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;
  };

  /**
   * See {IERC165-supportsInterface}.
   */
  supportsInterface(
    interfaceId: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  /**
   * See {IERC165-supportsInterface}.
   */
  "supportsInterface(bytes4)"(
    interfaceId: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  filters: {};

  estimate: {
    /**
     * See {IERC165-supportsInterface}.
     */
    supportsInterface(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    /**
     * See {IERC165-supportsInterface}.
     */
    "supportsInterface(bytes4)"(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;
  };
}
